### PR TITLE
Port to Gtk3

### PR DESCRIPTION
**Pull request by jku**
There's loads of calls to deprecated API there still. Didn't touch those because A) it's mostly GtkTable: I don't think it'll go away in near future; and B) I want to investigate Tomasz's connman-ui as a more modern alternative soon anyway

### CODE REVIEW

**Comment by pfl** [comment]
There is also a GNOME3 control-panel lookalike UI and an GNOME3 applet at https://github.com/jgke/connman-gtk and https://github.com/jgke/gnome-extension-connman. Please also investigate if you can reuse those components for your use cases.

**Comment by jku** [comment]
@pfl thanks. We don't use gnome-shell (in Yocto) so the extension is out but connman-gtk uses a GtkStatusicon -- that should work... Would you suggest that over https://github.com/tbursztyka/connman-ui ?

**Comment by jku** [comment]
@pfl anyway, I will update connman-gnome in Yocto (I'm upgrading everything to GTK+3 and the patchset is pretty big already... I don't want to delay it anymore). I can do that as a patch in yocto though if you don't want to touch this repo anymore.

**Comment by jku** [comment]
Closed this to get it out of my active PR list ;)

**Pull request closed without merging**
